### ISSUE TITLE
App fails to install on Ubuntu 9.10 amd64 using readme instructions

### ISSUE THREAD

**Issue by arobinson** [Constellation/crxmake#1]
The gem install is failing for me, any clue what is going on?

$ gem source -a http://gemcutter.org
http://gemcutter.org added to sources

$ sudo gem install crxmake
Building native extensions.  This could take a while...
ERROR:  Error installing crxmake:
    ERROR: Failed to build gem native extension.

/usr/bin/ruby1.8 extconf.rb
extconf.rb:1:in `require': no such file to load -- mkmf (LoadError)
    from extconf.rb:1

Gem files will remain installed in /var/lib/gems/1.8/gems/zipruby-0.3.6 for inspection.
Results logged to /var/lib/gems/1.8/gems/zipruby-0.3.6/ext/gem_make.out

$ gem --version
1.3.5

$ ruby --version
ruby 1.8.7 (2009-06-12 patchlevel 174) [x86_64-linux]

**Comment by arobinson** [comment]
Was a missing dependency in Ubuntu as described by this blog:
http://mentalized.net/journal/2006/01/24/no_such_file_to_load_mkmf/

**Comment by Constellation** [comment]
ruby package on Ubuntu (& debian) doesn't include some standard packages such as 'mkmf'.
so, install dev package and then you can install crxmake.

$ sudo apt-get install ruby1.8-dev

thanks.
